# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Spinei Dionis"
description: Blogging about Symfony and OOP best practices.

email: spinei.dionis@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
home_image: "/assets/images/home.png"
# blog cover
cover: ""

name: 'Spinei Dionis'
author: 'Spinei Dionis'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.spdionis.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/spdionis
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "l&amp;ur="

  - icon:	facebook
    url:	https://facebook.com/dionis.spinei
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/spdionis
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
